name: openlog-ci

on:
  push:
    branches:
      - '**'

jobs:

  build:
    name: build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Maven Package
        run: mvn -B clean package -DskipTests


  test:
    name: test
    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mysql:8.0

        env:
          MYSQL_DATABASE: openlog
          MYSQL_ROOT_PASSWORD: root

        ports:
          - 3306:3306

        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Maven Tests
        run: mvn -B compile test

  sonar:
    name: verify
    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mysql:8.0

        env:
          MYSQL_DATABASE: openlog
          MYSQL_ROOT_PASSWORD: root

        ports:
          - 3306:3306

        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=cdbros_openlog