name: openlog-ci

on:
  push:
    branches:
      - '**'

jobs:

  build:
    name: build
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - name: Maven Package
        run: mvn clean package -DskipTests


  test:
    name: test
    runs-on: ubuntu-18.04

    services:
      mysql:
        image: mysql:8.0

        env:
          MYSQL_DATABASE: openlog
          MYSQL_ROOT_PASSWORD: root

        ports:
          - 3306

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4

      - run: sed -i "s/localhost:3306/mysql:3306/g" src/test/resources/application.properties

      - name: Maven Tests
        run: mvn compile test